name: Deploy to EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_AUTH_SOCK: /tmp/ssh-XXXXXXzijz0Z/agent.1585
      SSH_AGENT_PID: 1586

    steps:
      - name: Setup SSH Connection
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      - name: Deploy code to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${EC2_USERNAME}@${EC2_HOST} "cd /home/ubuntu/Web_Resume && sudo rm -rf * && sudo rm -rf /var/www/html/* && git clone https://github.com/ritikvirus/Web_Resume.git && cd Web_Resume && sudo cp -r * /var/www/html/ && sudo service nginx restart"
