name: connect to ec2 instance

on:
  push:
    branch: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Enter Directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        command: |
          sudo rm -rf /home/ubuntu/web-site/*
          sudo rm -rf /var/www/html/*
          sudo git clone https://github.com/ritikvirus/Web_Resume.git /home/ubuntu/web-site/
          sudo mv /home/ubuntu/web-site/* /var/www/html/

    - name: Restart Nginx Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo systemctl restart nginx
