name: Deploy to EC2 Instance
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy code to EC2 Instance
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          server: ${{ secrets.EC2_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_SSH_KEY }}
          source: '.'
          target: '/home/ubuntu/Web_Resume'
          clean: true

      - name: Clone repo
        run: |
          cd /home/ubuntu/Web_Resume
          sudo rm -rf .
          git clone https://github.com/ritikvirus/Web_Resume.git .
      
      - name: Move files to /var/www/html
        run: sudo mv /home/ubuntu/Web_Resume/* /var/www/html/

      - name: Restart nginx
        run: sudo systemctl restart nginx
