name: Deploy to EC2 Instance
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: SSH into EC2 Instance
        run: ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} -p ${{ secrets.PORT }} "cd /home/ubuntu/Web_Resume && git pull && sudo mv ./* /var/www/html/ && sudo systemctl restart nginx"
