name: Deploy to EC2 instance

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Connect to EC2 instance and update website
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo rm -rf /home/ubuntu/web-site/*
          sudo rm -rf /var/www/html/*
          sudo cd /home/ubuntu/web-site
          sudo git clone https://github.com/ritikvirus/Web_Resume.git 
          sudo mv /home/ubuntu/web-site/* /var/www/html/
          
    - name: Restart Nginx server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo systemctl restart nginx
