name: connect to ec2 instance

on:
  push:
    branch: [main]
    
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clear /var/www/html directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo cd /home/ubuntu/web-site
          sudo rm -rf * \
          sudo git clone https://github.com/ritikvirus/Web_Resume.git \
          sudo rm -rf /var/www/html/* \
          sudo mv * /var/www/html/
          

    
    - name: Restart Nginx Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo systemctl restart nginx
