name: Deploy to Docker Hub

on:
  label:
    types: [created, edited]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

        with:
          fetch-depth: '0'
      - name: Minor version for each merge
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          WITH_V: true
          DRY_RUN: true

                       
        
      - name: Build Docker image
        run: docker build -t ritikvirus/portfolioubuntu:${{ steps.taggerDryRun.outputs.new_tag }} .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.D_USERNAME }} -p ${{ secrets.D_PASS }}

      - name: Push Docker image to Docker Hub
        run: docker push ritikvirus/portfolioubuntu:${{ steps.taggerDryRun.outputs.new_tag }}

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          HOSTNAME: ${{ secrets.HOST_IP }}
          USER_NAME: ${{ secrets.HOST_USER }}
        run: |
          echo "$PRIVATE_KEY" > key.pem && chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu &&
            sudo docker stop $(docker ps -a -q) &&
            sudo docker rm $(docker ps -a -q) &&
            sudo docker rmi -f $(docker images -q) &&
            sudo docker pull ritikvirus/portfolioubuntu:${{ steps.taggerDryRun.outputs.new_tag }} &&
            sudo docker rm springboot || true &&
            sudo docker run -d -p 8080:80 --name portfolio ritikvirus/portfolioubuntu:${{ steps.taggerDryRun.outputs.new_tag }}
          '


      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The Portfolio {{ EVENT_PAYLOAD.repository.full_name }} IMAGE_NAME:- ritikvirus/portfolioubuntu:${{ steps.taggerDryRun.outputs.new_tag }} URL :- https://ritikvirus.info has been deployed.'


      - name: Minor version for each merge
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
